# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{- if .Values.nats.groupsio_services_kv_bucket.creation -}}
---
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.groupsio_services_kv_bucket.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nats.groupsio_services_kv_bucket.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.groupsio_services_kv_bucket.name }}
  history: {{ .Values.nats.groupsio_services_kv_bucket.history }}
  storage: {{ .Values.nats.groupsio_services_kv_bucket.storage }}
  maxValueSize: {{ .Values.nats.groupsio_services_kv_bucket.maxValueSize }}
  maxBytes: {{ .Values.nats.groupsio_services_kv_bucket.maxBytes }}
  compression: {{ .Values.nats.groupsio_services_kv_bucket.compression }}
{{- end }}
---
{{- if .Values.nats.groupsio_mailing_lists_kv_bucket.creation -}}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nats.groupsio_mailing_lists_kv_bucket.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.name }}
  history: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.history }}
  storage: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.storage }}
  maxValueSize: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.maxValueSize }}
  maxBytes: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.maxBytes }}
  compression: {{ .Values.nats.groupsio_mailing_lists_kv_bucket.compression }}
{{- end }}
