swagger: "2.0"
info:
    title: Mailing List Service
    description: Service for managing mailing lists in LFX
    version: "1.0"
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /livez:
        get:
            tags:
                - mailing-list
            summary: livez mailing-list
            description: Liveness probe endpoint
            operationId: mailing-list#livez
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /readyz:
        get:
            tags:
                - mailing-list
            summary: readyz mailing-list
            description: Readiness probe endpoint
            operationId: mailing-list#readyz
            responses:
                "200":
                    description: OK response.
                "503":
                    description: Service Unavailable response.
            schemes:
                - http
